apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.target.name | default (printf "%s-secret" .Release.Name) }}
    creationPolicy: Owner
  dataFrom:
    {{- range .Values.externalSecret.dataFrom }}
    - extract:
        key: {{ .extract.key }}
    {{- end }}