apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.secretStore.region | default "us-east-1" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStore.secretRef.accessKeyIDSecretRef.name }}
            key: {{ .Values.secretStore.secretRef.accessKeyIDSecretRef.key }}
          secretAccessKeySecretRef:
            name: {{ .Values.secretStore.secretRef.secretAccessKeySecretRef.name }}
            key: {{ .Values.secretStore.secretRef.secretAccessKeySecretRef.key }}